services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      dojo-tracker-app:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./certbot:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --non-interactive --agree-tos -d dojo-tracker.japan-dojo.com
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot:/var/www/certbot
  dojo-tracker-app:
    image: "japandojo/dojo-tracker-server:${TAG}"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/db/data/data.db
      - FRONTEND_URL=https://mahjong-tma-1.web.app
      - BOT_URL=https://t.me/japan_dojo_bot/tracker
    env_file:
      - .env
    expose:
      - 3000
    volumes:
      - ./db/data:/app/db/data
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  sqlite-web:
    image: coleifer/sqlite-web
    restart: unless-stopped
    depends_on:
      dojo-tracker-app:
        condition: service_healthy
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - SQLITE_DATABASE=/data/data.db
    volumes:
      - ./db/data:/data
